### ISSUE TITLE
add continuous integration for this repo

### ISSUE THREAD

**Issue by edonyM** [edonyM/toolkitem#14]
* `.travis.yml` file
```yml
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
```
* `requirements.txt` file
* test modula
